import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

import ReactQueryProvider from "@/components/Providers/ReactQueryProvider";
import { Toaster } from "@/components/ui/toaster";

const noto_sans = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${noto_sans.className} scroll-smooth bg-gray-200 antialiased`}
      >
        <ReactQueryProvider>
          {/* <Navbar /> */}
          {children}
          <Toaster />
          {/* <Footer /> */}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
