import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import ReactQueryProvider from "@/components/Providers/ReactQueryProvider";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} scroll-smooth bg-gray-200 antialiased`}
      >
        <ReactQueryProvider>
          {/* <Navbar /> */}
          {children}
          <Toaster />
          {/* <Footer /> */}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
